spring:
  profiles:
    active: ${PROFILE:dev}
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false

---

spring:
  profiles: test
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: 1234
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
      
---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/tmp/h2/notasfiscais/notasfiscais;AUTO_SERVER=TRUE
#    url: jdbc:h2:file:C:\Developer\H2\notasfiscais\notasfiscais;AUTO_SERVER=TRUE
    username: sa
    password: 123
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: prd
  h2:
    console:
      enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_LOCATION:localhost}:${DB_PORT:5432}/${DB_NAME:notasfiscais}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
